/*
 * Copyright (c) 2022-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package pub.ihub.plugin.java

import groovy.transform.CompileStatic
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

/**
 * 生成 lombok.config 文件的任务（Configuration-Cache 友好）。
 *
 * <p>历史背景：Lombok 插件 6.1.0 之后不再自动生成 lombok.config 文件，
 * 详见 https://github.com/freefair/gradle-plugins/issues/379。
 * 本任务接管该职责，使用 {@code @OutputFile} 实现增量构建与 CC 兼容。</p>
 *
 * <p>若项目已存在 lombok.config 文件，则任务不会覆盖。</p>
 *
 * @author henry
 * @since 1.9.5
 */
@CompileStatic
@DisableCachingByDefault(because = '生成动作极轻；输出已通过 @OutputFile 增量化')
abstract class IHubLombokConfigTask extends DefaultTask {

    /**
     * lombok.config 输出位置，通常为 project root 下的 lombok.config。
     */
    @OutputFile
    abstract RegularFileProperty getLombokConfigFile()

    /**
     * lombok.config 中要写入的 KV 对。
     */
    @Input
    abstract MapProperty<String, Object> getEntries()

    @TaskAction
    void generate() {
        File file = lombokConfigFile.get().asFile
        // 不覆盖本地已有 lombok.config
        if (file.exists()) {
            logger.info "lombok.config already exists at ${file.absolutePath}, skip generation."
            return
        }
        file.parentFile?.mkdirs()
        file.text = "# This file is generated by the 'pub.ihub.plugin.ihub-java' gradle plugin.\n" +
            entries.get().collect { k, v -> "$k = $v" }.join('\n') + '\n'
    }

}
