[versions]
ihub = '1.1.6'
spring-dependency = '1.1.0'
freefair = '8.1.0'
ben-manes = '0.47.0'
byte-buddy = '1.12.12'
jmolecules = '1.6.0'
jonhrengelman = '0.5.0'
springdoc = '1.6.0'
spring-boot = '3.1.1'
graalvm = '0.9.23'
kotlin = '1.9.0'

[libraries]
ihub-core = { module = 'pub.ihub.lib:ihub-core', version.ref = 'ihub' }
dependency-management = { module = 'io.spring.gradle:dependency-management-plugin', version.ref = 'spring-dependency' }
freefair-utils = { module = 'io.freefair.gradle:plugin-utils', version.ref = 'freefair' }
freefair-git = { module = 'io.freefair.gradle:git-plugin', version.ref = 'freefair' }
freefair-lombok = { module = 'io.freefair.gradle:lombok-plugin', version.ref = 'freefair' }
freefair-github = { module = 'io.freefair.gradle:github-plugin', version.ref = 'freefair' }
freefair-settings = { module = 'io.freefair.gradle:settings-plugin', version.ref = 'freefair' }
ben-manes-versions = { module = 'com.github.ben-manes:gradle-versions-plugin', version.ref = 'ben-manes' }
byte-buddy = { module = 'gradle.plugin.net.bytebuddy:byte-buddy-gradle-plugin', version.ref = 'byte-buddy' }
jmolecules-bytebuddy = { module = 'org.jmolecules.integrations:jmolecules-bytebuddy', version.ref = 'jmolecules' }
johnrengelman-processes = { module = 'com.github.johnrengelman.processes:com.github.johnrengelman.processes.gradle.plugin', version.ref = 'jonhrengelman' }
springdoc-openapi = { module = 'org.springdoc:springdoc-openapi-gradle-plugin', version.ref = 'springdoc' }
spring-boot = { module = 'org.springframework.boot:spring-boot-gradle-plugin', version.ref = 'spring-boot' }
native = { module = 'org.graalvm.buildtools:native-gradle-plugin', version.ref = 'graalvm' }
kotlin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin' }

[plugins]
testkit = { id = 'pl.droidsonroids.jacoco.testkit', version = '1.0.12' }
