[versions]
ihub = '1.1.8'
freefair = '8.1.0'

[libraries]
ihub-core = { module = 'pub.ihub.lib:ihub-core', version.ref = 'ihub' }
dependency-management = { module = 'io.spring.gradle:dependency-management-plugin', version = '1.1.2' }
freefair-utils = { module = 'io.freefair.gradle:plugin-utils', version.ref = 'freefair' }
freefair-git = { module = 'io.freefair.gradle:git-plugin', version.ref = 'freefair' }
freefair-lombok = { module = 'io.freefair.gradle:lombok-plugin', version.ref = 'freefair' }
freefair-github = { module = 'io.freefair.gradle:github-plugin', version.ref = 'freefair' }
freefair-settings = { module = 'io.freefair.gradle:settings-plugin', version.ref = 'freefair' }
ben-manes-versions = { module = 'com.github.ben-manes:gradle-versions-plugin', version = '0.47.0' }
byte-buddy = { module = 'gradle.plugin.net.bytebuddy:byte-buddy-gradle-plugin', version = '1.12.12' }
jmolecules-bytebuddy = { module = 'org.jmolecules.integrations:jmolecules-bytebuddy', version = '1.6.0' }
johnrengelman-processes = { module = 'com.github.johnrengelman.processes:com.github.johnrengelman.processes.gradle.plugin', version = '0.5.0' }
springdoc-openapi = { module = 'org.springdoc:springdoc-openapi-gradle-plugin', version = '1.6.0' }
spring-boot = { module = 'org.springframework.boot:spring-boot-gradle-plugin', version = '3.1.2' }
native = { module = 'org.graalvm.buildtools:native-gradle-plugin', version = '0.9.23' }
kotlin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version = '1.9.0' }

[plugins]
testkit = { id = 'pl.droidsonroids.jacoco.testkit', version = '1.0.12' }
