name: Dependency Review
on:
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  dependency-review:
    if: ${{ github.repository_owner == 'ihub-pub' }}
    permissions:
      contents: read
    name: Dependency Review Scan
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@f46c48ed6d4f1227fb2d9ea62bf6bcbed315589e # v3.0.4
