name: Docs Pages

on:
  push:
    branches: main
    paths:  
      - 'docs/**'
      - '.github/workflows/doc.yml'

permissions:
  contents: read

jobs:
  docs:
    if: ${{ github.repository_owner == 'ihub-pub' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Use Node.js 18.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: docs
      - name: Build VuePress site
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: npm run build
        working-directory: docs

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@1d6ee9b181a81033a16bd707a1401afa978daab4 # v5.0.0
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
