name: Build
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    if: ${{ github.repository_owner == 'ihub-pub' }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Testspace Setup CLI
        uses: testspace-com/setup-testspace@ee1482f978eb5010ec27b6f6372904f01f2edd68 # v1.0.6
        with:
          domain: ${{ github.repository_owner }}

      - name: Chmod
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629 # v2.4.2
        with:
          arguments: --no-build-cache test -DiHubTest.failFast=true

      - name: Upload Coverage Reports
        if: ${{ github.event_name == 'schedule' && github.repository_owner == 'ihub-pub' }}
        uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3.1.3

      - name: Publish Results to Testspace
        run: testspace */build/test-results/test/*.xml */build/reports/*/test/*.xml

      - name: Upload Test Result
        if: ${{ failure() }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: tests
          path: |
            */build/reports/tests
          retention-days: 1
